### DISCUSSION TITLE
Floating Lidar File Format Standardization Development - 2024

### DISCUSSION THREAD

**Discussion by stephenholleran** [IEA-Task-43/digital_wra_data_standard#268] [General]
## 19-Sep-2024 First Meeting

**Attendance:**
Stephen Holleran (BrightWind), Jon Upton (Shell), Ryan Scott (RWE), Gibson Kersting (RWE), Jason Fields (RES), Amit Bohara (Altosphere), Anselme Troiville (Green Rebel), Hanna Torrens-Spence (BrightWind), Jose Miguel Garro (Eolos), Felix Kelberlau (Fugro), Kenneth John (RINA), Maximillian Schuberth (Recons), Richard Khaira-Creswell (Axys), David McCracken (BP), Philip Hargreaves (TGS) [15]

### Minutes:
1. Quick intros.
2. Went through the presentation https://docs.google.com/presentation/d/1w-VNQEwlnxh1dC20qUz2uNqeTybNoFB18HVZ2esUNgg/edit?usp=sharing 
3. A discussion followed.
4. Everyone on the call was committed to develop this standard.

### Actions
- [x] Prepare for next meeting in 2 weeks. Objective to pull from the data model the metadata we want to capture.

**Comment by stephenholleran** [comment]
## 17-Oct-2024 2nd Meeting

**Attendance:**
Stephen Holleran (BrightWind), Hanna Torrens-Spence (BrightWind), Jose Miguel Garro (Eolos), Ryan Scott (RWE),  Jon Upton (Shell), Anselme Troiville (Green Rebel), Philip Hargreaves (TGS), Felix Kelberlau (Fugro) (temporarily), Amit Bohara (Altosphere) [9].


### Minutes:
1. Quick intros.
2. We had to skip the call on the 3rd Oct due to the ACP conf.
3. I am thinking about this standard file format in 3 parts:
   1. File name and extension
   3. Header
   4. Column names
4. I think we should start with the **header** first. The below example is following the WRA Data Model from `measurement_location` to `logger_main_config`.
    ```yaml
    name: Site X - FLS 01
    latitude_ddeg: 53.5017
    longitude_ddeg: -19.0966
    measurement_station_type: floating_lidar
    logger_main_config:
      - logger_oem: ZX Lidars
        logger_model_name: 300M
        logger_serial_number: 1234
        logger_firmware_version: v12345
        logger_id: 1234
        logger_name: FLS1
        offset_from_utc_hrs: 0.0
        averaging_period_minutes: 10
        timestamp_is_end_of_period: True
        lidar_config:
            flow_corrections_applied: false
            logger_stated_device_datum_plane_height_m: 2
            logger_stated_device_orientation_deg: 3
      - logger_oem: Nortek
        logger_model_name: Signature250
        logger_serial_number: 1234567
        offset_from_utc_hrs: 0.0
        averaging_period_minutes: 10
    ```   
   1. Very minimal is actually required for the data model. The minimum would be `name`, `latitude_ddeg`, `longitude_ddeg` and `measurement_station_type`.
   3. If `logger_main_config` is provided, the minimal from that would be `logger_oem` and `logger_serial_number`.
   4. Leaving out the `date_from` and `date_to` as this config is to cover the config used to produce the timeseries data in the file. **Yes, we all agree.**
   7. Using YAML format instead of JSON to make it more readable and simple. We could just use the WRA Data Model JSON but I think it would be too long and complicated? JSON equivalent: **Best to stick with JSON as it is one less thing to explain. And we are all used to JSON and the data model is already in JSON.**
    ```json
    {
	    "name": "Site X - FLS 01",
	    "latitude_ddeg": 53.5017,
	    "longitude_ddeg": -19.0966,
	    "measurement_station_type_id": "floating_lidar",
	    "logger_main_config": 
	    [{
		    "logger_oem": "ZX Lidars",
		    "logger_model_name": "300M",
		    "logger_serial_number": "1234",
		    "logger_firmware_version": "v12345",
		    "logger_id": "1234",
		    "logger_name": "FLS1",
		    "offset_from_utc_hrs": 0.0,
		    "averaging_period_minutes": 10,
		    "timestamp_is_end_of_period": true,
		    "lidar_config":
		    {
			    "flow_corrections_applied": false,
			    "logger_stated_device_datum_plane_height_m": 2,
			    "logger_stated_device_orientation_deg": 3
		    }
	    },{
		    "logger_oem": "Nortek",
		    "logger_model_name": "Signature250",
		    "logger_serial_number": "1234567",
		    "offset_from_utc_hrs": 0.0,
		    "averaging_period_minutes": 10,
	    }]
    }
    ```
   9. Do we need a section to capture 'file format version', 'software processing version', 'firmware version', ???? **Yes. What are they:**
      1. 'file format version' is the version of this file we are developing now.
      2. 'software processing version' could be the version of the floating lidar OEM pipeline to produce the file.
      3. 'buoy version' Do have buoy version numbers but probably not that important to capture. But could be used to verify the type verification. No harm in including as all these may be optional.
      4. Maybe these should be compulsory to set a standard that consumers of the data will know that this info is in there and any new entrants to the market would be encourage to have good processes in place for example, that they have good processes to track their pipeline process and can trace which version of the ZPH2CSV converter was used.
      5. We'll come back to this again in the next call.
   11. I think the `measurement_point` section of the data model can be covered by a structured column name of the timeseries data? **Yes we think this would be a good thing. It is not deviating from the data model as such, we are just not including that part of the data model in the header.**
5. **Column names**: these could contain the minimal information so we can avoid having a very large header with measurement point information.
   1. Format: `<sensor_type>_<serial_number>_<measurement_type>_<height>_<measurement_units>_<statistic_type>`
      Example: `lidar_1234_wind_speed_110_m/s_avg`
   2. Continue this discussion on the next call.

### Actions
- [x] Think about the extra section to capture versions.
- [x] As well as prepare for next call to discuss column name format and file name.
